### ISSUE TITLE
Implement calculator for GSM8k

### ISSUE THREAD

**Issue by zhangir-azerbayev** [EleutherAI/math-lm#1]
[reference implementation](https://github.com/openai/grade-school-math/blob/master/grade_school_math/calculator.py)

Best done as a pr to the harness.

**Comment by haileyschoelkopf** [comment]
If the proofGPT-v0.1-6.7b model already gets nonzero performance on gsm8k (and so is good enough for testing how well calculator works) I might be able to implement calculator over the next week. Shouldn't take too long

**Comment by zhangir-azerbayev** [comment]
Taking the program synthesis approach instead.
