### ISSUE TITLE
Mathematica and Matlab

### ISSUE THREAD

**Issue by zhangir-azerbayev** [EleutherAI/math-lm#16]
Because of data quality issues in the stack, our code dataset currently doesn't include mathematica and matlab code. 

A good contribution would be to download mathematica and matlab code from [BigQuery](https://codelabs.developers.google.com/codelabs/bigquery-github#0) and preprocess it.

Preprocessing matlab will only require setting up a language filter and dealing with standard data quality issues. Fully preprocessing mathematica data will require writing a script to convert notebooks to markdown: this is a little annoying but doable.

Here's an example SQL query you can use to select all the `.m` files from the Github database
```sql
SELECT
f.repo_name,
f.path,
c.copies,
c.size,
c.content,
l.license
FROM
`bigquery-public-data.github_repos.files` AS f
JOIN
`bigquery-public-data.github_repos.contents` AS c
ON
f.id = c.id
JOIN
`bigquery-public-data.github_repos.licenses` AS l
ON
f.repo_name = l.repo_name
WHERE
NOT c.binary
AND ((f.path LIKE '%.m')
AND (c.size BETWEEN 1024
AND 1048575))
```

**Comment by haileyschoelkopf** [comment]
I could probably take care of at least Mathematica--do you have a BigQuery account you've been using / would you be willing to point me to where you have been downloading other bigquery data (LILY servers?)

**Comment by wellecks** [comment]
Based on #29, using github search could be effective here. A good place to start is to modify the process_github.py script to scrape Mathematica/Matlab code, then add language-specific filters based on the observed data quality.

**Comment by wellecks** [comment]
@leo-du is looking into this!

**Comment by zhangir-azerbayev** [comment]
We have matlab now. 

For mathematica, you'd have to parse the raw notebook files. Not a good use of time right now. 

Closing.
