### ISSUE TITLE
Additional languages from Stack

### ISSUE THREAD

**Issue by wellecks** [EleutherAI/math-lm#24]
These languages have a heavy focus on proofs/verification, but aren't in our current filter of the Stack:

- [ ] ~~Coq: https://huggingface.co/datasets/bigcode/the-stack-dedup/tree/main/data/coq~~
- [ ] Agda: https://huggingface.co/datasets/bigcode/the-stack-dedup/tree/main/data/agda
- [ ] Idris: https://huggingface.co/datasets/bigcode/the-stack-dedup/tree/main/data/idris

Adding them to the corpus might be beneficial for downstream formal proof-related tasks.

**Comment by wellecks** [comment]
The Coq split in the stack only has 31 documents: noise, Coq makefiles, and a few functions. It's not worth adding.

**Comment by wellecks** [comment]
Sounds good!

Compared to Agda, Idris seems to have more general-domain functional programming data (e.g. `idris-jvm`, `idris-erlang`, `idris-webassembly`). I think it makes sense since Idris is used as a general-purpose language. We might exclude it if we want strictly proof/math-related code. On the other hand, it might still be beneficial - hard to say.

**Comment by zhangir-azerbayev** [comment]
Added in commit [b1e74](https://github.com/EleutherAI/math-lm/commit/b1e746ab3e2590472ec1d127d2fccc53b2433dc1). Will PR tonight.
