### ISSUE TITLE
Date cutoff for github code

### ISSUE THREAD

**Issue by wellecks** [EleutherAI/math-lm#31]
We would like a fixed date cutoff for the code subset (i.e., the latest date at which a source file was modified). 

The [process_github.py](https://github.com/EleutherAI/math-lm/blob/main/proof-pile-v2/source_code/process_github.py) script uses the most recent commit from each repository, meaning that the date cutoff will vary based on when the script is run. Modify [process_github.py](https://github.com/EleutherAI/math-lm/blob/main/proof-pile-v2/source_code/process_github.py)  to use the last commit that is prior to a specified cutoff.

**Comment by leo-du** [comment]
Attempted in #32! Let me know whether it fixes the problem.
