### ISSUE TITLE
Citation for this repo

### ISSUE THREAD

**Issue by brando90** [EleutherAI/math-lm#34]
I created this one for now:
```
@online{eleutherai2023,
    author = {EleutherAI},
    title = {math-lm},
    year = {n.d.},
    url = {https://github.com/EleutherAI/math-lm},
    urldate = {2023-06-12},
    note = {Accessed: 2023-06-12}
}
```

**Comment by zhangir-azerbayev** [comment]
Sorry for the late reply.

The dataset and the models aren't officially released. Of course it's fine to talk about or reference any of our public code, but if possible, please mention that it's still a WIP until the official release.
