### ISSUE TITLE
Premise Selection (Eval Task)

### ISSUE THREAD

**Issue by haileyschoelkopf** [EleutherAI/math-lm#6]

**Comment by zhangir-azerbayev** [comment]
@albertqjiang Any updates on this?

**Comment by albertqjiang** [comment]
Sorry I forgot about this. The data has been released and I've started the eval creation.

Tentative format:

Input to the LM:

Isabelle proof state: ${proof_state}
Choose the index of the correct premise from the following:
(1) ${premise1_name}: ${prmeise1_statement}
...
(8) ...

Ground truth output:

${index_of_the_ground_truth}

Postprocessing: leaving only numeric values before comparing.

It looks like the MultipleChoiceTask can handle the long context nicely. Will inherit from that.

**Comment by zhangir-azerbayev** [comment]
Since we're doing an isabelle theorem proving task, I'm closing this issue.
