### ISSUE TITLE
Security warning on --recurse-submodule (of llemma_formal2formal)

### ISSUE THREAD

**Issue by jabowery** [EleutherAI/math-lm#82]
Apparently [the solution to this security warning](https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/) is to execute:
`ssh-keygen -R github.com`
However, the actual solution is to, after the above command, add all of GitHub's SSH key fingerprints to `~/.ssh/authorizedkeys`:

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints

My reason for posting this issue here is that even though this issue originated last March, I've cloned several repositories since then without ever encountering this warning until attempting this repository.  Moreover, none of the other repositories required the ` --recurse-submodule` option.

**Comment by zhangir-azerbayev** [comment]
Fixed by #86
